// Run against the local production preview only: node scripts/check-library.mjs
import assert from 'node:assert/strict';
const base = 'http://127.0.0.1:5175';
const owner = `integration-${crypto.randomUUID()}`;
const headers = { 'oai-authenticated-user-id': owner, 'oai-authenticated-user-email': 'test@example.invalid', origin: base };
const request = async (path, options = {}) => {
  const response = await fetch(base + path, { ...options, signal: AbortSignal.timeout(15000), headers: { ...headers, connection: 'close', ...options.headers } });
  return new Response(await response.arrayBuffer(), { status: response.status, headers: response.headers });
};
const read = async () => (await request('/api/library')).json();
const write = async (operation, revision) => request('/api/library', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...operation, revision }) });
assert.equal((await fetch(base + '/api/library')).status, 401);
let library = await read();
assert.equal(library.settings.adminName, 'Thọ Nguyễn');
assert.equal((await write({ action: 'album', slug: 'test', name: 'Kiểm thử', time: '' }, library.revision)).status, 200);
assert.equal((await write({ action: 'settings', adminName: 'Stale', title: 'Stale' }, library.revision)).status, 409);
library = await read();
assert.ok(library.albums.some(a => a.slug === 'test'));
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9XkAAAAASUVORK5CYII=', 'base64');
const form = new FormData();
form.set('file', new File([png], 'test.png', { type: 'image/png' }));
form.set('album', 'test'); form.set('width', '1'); form.set('height', '1');
form.set('uploadId', crypto.randomUUID());
const upload = await request('/api/library/upload', { method: 'POST', body: form });
assert.equal(upload.status, 201, await upload.clone().text());
const { id, sha256 } = await upload.json();
const expectedHash = Buffer.from(await crypto.subtle.digest('SHA-256', png)).toString('hex');
assert.equal(sha256, expectedHash);
const retry = await request('/api/library/upload', { method: 'POST', body: form });
assert.equal(retry.status, 201);
assert.equal((await retry.json()).id, id);
assert.equal((await read()).photos.filter(p => p.id === id).length, 1);
assert.equal((await request('/api/library/storage')).status, 200);
const photo = await request(`/api/library/photo/${id}`);
assert.equal(photo.status, 200);
assert.equal(photo.headers.get('X-Original-SHA256'), expectedHash);
assert.deepEqual(Buffer.from(await photo.arrayBuffer()), png);
assert.equal((await request(`/api/library/photo/${id}`, { headers: { 'oai-authenticated-user-id': owner + '-other' } })).status, 404);
library = await read();
assert.equal((await write({ action: 'deleteAlbum', slug: 'test' }, library.revision)).status, 400);
assert.equal((await write({ action: 'movePhotos', ids: [id], album: 'pre-wedding' }, library.revision)).status, 200);
library = await read();
assert.equal(library.photos.find(p => p.id === id).album, 'pre-wedding');
assert.equal((await write({ action: 'deletePhotos', ids: [id] }, library.revision)).status, 200);
assert.equal((await request(`/api/library/photo/${id}`)).status, 404);
library = await read();
assert.equal((await write({ action: 'deleteAlbum', slug: 'test' }, library.revision)).status, 200);
library = await read();
assert.equal((await write({ action: 'settings', adminName: 'Thọ Nguyễn', title: 'Thư viện kiểm thử' }, library.revision)).status, 200);
assert.equal((await read()).settings.title, 'Thư viện kiểm thử');
assert.equal((await request('/api/uploads/presign', { method: 'POST' })).status, 410);
assert.equal((await request('/api/library', { method: 'POST', headers: { origin: 'https://invalid.example', 'content-type': 'application/json' }, body: '{}' })).status, 403);
console.log('PASS: authentication, origin protection, album CRUD, revisions, upload, exact original bytes, owner isolation, move/delete photos, persistent settings.');
